### ISSUE TITLE
multi gpu training aishell error

### ISSUE THREAD

**Issue by zh794390558** [hirofumi0810/neural_sp#150]
```
./run.sh --gpu 0,1,2,3 --stage 4 --stop_stage 4 --conf conf/asr/blstm_las.yaml 
```

```
Traceback (most recent call last):
  File "/e2e_asr/neural_sp/examples/aishell/s5/../../../neural_sp/bin/asr/train.py", line 501, in <module>
    save_path = pr.runcall(main)
  File "/e2e_asr/neural_sp/tools/miniconda/lib/python3.7/cProfile.py", line 121, in runcall
    return func(*args, **kw)
  File "/e2e_asr/neural_sp/examples/aishell/s5/../../../neural_sp/bin/asr/train.py", line 309, in main
    teacher=teacher, teacher_lm=teacher_lm)
  File "/e2e_asr/neural_sp/tools/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/e2e_asr/neural_sp/tools/miniconda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/e2e_asr/neural_sp/tools/miniconda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/e2e_asr/neural_sp/tools/miniconda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/e2e_asr/neural_sp/tools/miniconda/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
StopIteration: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/e2e_asr/neural_sp/tools/miniconda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/e2e_asr/neural_sp/tools/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/e2e_asr/neural_sp/neural_sp/models/seq2seq/speech2text.py", line 248, in forward
    loss, observation = self._forward(batch, task, teacher, teacher_lm)
  File "/e2e_asr/neural_sp/neural_sp/models/seq2seq/speech2text.py", line 258, in _forward
    eout_dict = self.encode(batch['xs'], 'all')
  File "/e2e_asr/neural_sp/neural_sp/models/seq2seq/speech2text.py", line 373, in encode
    xs = pad_list([np2tensor(x, self.device).float() for x in xs], 0.)
  File "/e2e_asr/neural_sp/neural_sp/models/seq2seq/speech2text.py", line 373, in <listcomp>
    xs = pad_list([np2tensor(x, self.device).float() for x in xs], 0.)
  File "/e2e_asr/neural_sp/neural_sp/models/base.py", line 58, in device
    return next(self.parameters()).device
StopIteration
```

how to fix this?
commit 66a88653890dbca554cf9e983867920d744591bd

**Comment by hirofumi0810** [comment]
I think this depends on the pytorch version. Which version did you use?

**Comment by zh794390558** [comment]
'1.5.1+cu101'

**Comment by hirofumi0810** [comment]
OK. I will fix it.

**Comment by FzuGsr** [comment]
Hi, hiro
I made an error running the aishell training language model with multiple GPUs.
It seems to be a data parallelism error:
```
  File "/opt/sean/neural_sp/neural_sp/models/data_parallel.py", line 42, in scatter
    res = [{k: scatter_map(v, i) for k, v in inputs.items()} for i in range(len(self.device_ids))]
  File "/opt/sean/neural_sp/neural_sp/models/data_parallel.py", line 42, in <listcomp>
   res = [{k: scatter_map(v, i) for k, v in inputs.items()} for i in range(len(self.device_ids))]
AttributeError: 'numpy.ndarray' object has no attribute 'items'
```
