### ISSUE TITLE
bash run error

### ISSUE THREAD

**Issue by xiexukang** [hirofumi0810/neural_sp#226]
Traceback (most recent call last):
  File "/home/qidongchen/xxk/neural_sp/examples/aishell/s5/../../../neural_sp/bin/lm/train.py", line 341, in <module>
    save_path = pr.runcall(main)
  File "/home/qidongchen/anaconda3/envs/torch1.15/lib/python3.7/cProfile.py", line 121, in runcall
    return func(*args, **kw)
  File "/home/qidongchen/xxk/neural_sp/examples/aishell/s5/../../../neural_sp/bin/lm/train.py", line 176, in main
    benchmark=not is_transformer and args.cudnn_benchmark)
  File "/home/qidongchen/xxk/neural_sp/neural_sp/models/base.py", line 101, in cudnn_setting
    assert self.use_cuda
AssertionError
we use train.py not error, but we use bash run ， it show not cuda,my torch have gpu support

**Comment by hirofumi0810** [comment]
@xiexukang Can you show me your command to start training on the terminal?

**Comment by jinggaizi** [comment]
i had the same problem, i check the run.sh and i set the variable gpu is to 8. At first I thought it's the number of gpu, fix it and will be ok
